# pdsite configuration

theme: default
inputextension: .md
inputfolder: dither-spec/
outputfolder: static/spec

# Site-wide template variables

sitename: "Dither Spec"
# pagetitle-suffix: "Dither Specification"
footer: '<a class="navbar-link" href="https://github.com/libdither/dither-spec">GitHub Repo</a>'
