# pdsite configuration

theme: default
inputextension: .md
inputfolder: src/
outputfolder: static/spec/

# Site-wide template variables

sitename: "Dither Spec"
pagetitle-suffix: ""
# footer: "My pdsite footer"
